import 'package:flutter/material.dart';

class TxModel {
  final String id;
  final String title;
  final String category;
  final String type; // 'Pemasukan' | 'Pengeluaran'
  final int amount;
  final DateTime date;
  final String? note;
  final IconData icon;
  final Color color;

  TxModel({
    required this.id,
    required this.title,
    required this.category,
    required this.type,
    required this.amount,
    required this.date,
    this.note,
    required this.icon,
    required this.color,
  });
}

final List<TxModel> dummyTransactions = [
  TxModel(
    id: '1',
    title: 'Gaji Bulanan',
    category: 'Gaji',
    type: 'Pemasukan',
    amount: 8500000,
    date: DateTime(2026, 4, 1),
    note: 'Gaji April',
    icon: Icons.work_outline,
    color: Colors.green,
  ),
  TxModel(
    id: '2',
    title: 'Makan Siang',
    category: 'Makan',
    type: 'Pengeluaran',
    amount: 45000,
    date: DateTime(2026, 4, 2),
    icon: Icons.restaurant_outlined,
    color: Colors.orange,
  ),
  TxModel(
    id: '3',
    title: 'Tagihan Listrik',
    category: 'Tagihan',
    type: 'Pengeluaran',
    amount: 320000,
    date: DateTime(2026, 4, 3),
    icon: Icons.bolt_outlined,
    color: Colors.amber,
  ),
  TxModel(
    id: '4',
    title: 'Belanja Bulanan',
    category: 'Belanja',
    type: 'Pengeluaran',
    amount: 750000,
    date: DateTime(2026, 4, 4),
    icon: Icons.shopping_bag_outlined,
    color: Colors.purple,
  ),
  TxModel(
    id: '5',
    title: 'Transport Ojek',
    category: 'Transport',
    type: 'Pengeluaran',
    amount: 35000,
    date: DateTime(2026, 4, 5),
    icon: Icons.two_wheeler_outlined,
    color: Colors.teal,
  ),
  TxModel(
    id: '6',
    title: 'Freelance Design',
    category: 'Pendapatan Lain',
    type: 'Pemasukan',
    amount: 1500000,
    date: DateTime(2026, 4, 6),
    note: 'Project logo',
    icon: Icons.brush_outlined,
    color: Colors.blue,
  ),
  TxModel(
    id: '7',
    title: 'Tagihan Internet',
    category: 'Tagihan',
    type: 'Pengeluaran',
    amount: 250000,
    date: DateTime(2026, 4, 7),
    icon: Icons.wifi_outlined,
    color: Colors.indigo,
  ),
  TxModel(
    id: '8',
    title: 'Kopi & Snack',
    category: 'Makan',
    type: 'Pengeluaran',
    amount: 65000,
    date: DateTime(2026, 4, 8),
    icon: Icons.coffee_outlined,
    color: Colors.brown,
  ),
  TxModel(
    id: '9',
    title: 'Bonus Kinerja',
    category: 'Gaji',
    type: 'Pemasukan',
    amount: 2000000,
    date: DateTime(2026, 4, 10),
    icon: Icons.card_giftcard_outlined,
    color: Colors.green,
  ),
  TxModel(
    id: '10',
    title: 'Bensin Motor',
    category: 'Transport',
    type: 'Pengeluaran',
    amount: 80000,
    date: DateTime(2026, 4, 11),
    icon: Icons.local_gas_station_outlined,
    color: Colors.red,
  ),
  TxModel(
    id: '11',
    title: 'Makan Malam',
    category: 'Makan',
    type: 'Pengeluaran',
    amount: 120000,
    date: DateTime(2026, 4, 12),
    icon: Icons.restaurant_outlined,
    color: Colors.orange,
  ),
  TxModel(
    id: '12',
    title: 'Tagihan Air',
    category: 'Tagihan',
    type: 'Pengeluaran',
    amount: 85000,
    date: DateTime(2026, 4, 13),
    icon: Icons.water_drop_outlined,
    color: Colors.cyan,
  ),
  TxModel(
    id: '13',
    title: 'Uang Saku Anak',
    category: 'Keluarga',
    type: 'Pengeluaran',
    amount: 200000,
    date: DateTime(2026, 4, 14),
    icon: Icons.child_care_outlined,
    color: Colors.pink,
  ),
  TxModel(
    id: '14',
    title: 'Pendapatan Sewa',
    category: 'Pendapatan Lain',
    type: 'Pemasukan',
    amount: 1200000,
    date: DateTime(2026, 4, 15),
    icon: Icons.home_outlined,
    color: Colors.green,
  ),
  TxModel(
    id: '15',
    title: 'Obat & Kesehatan',
    category: 'Kesehatan',
    type: 'Pengeluaran',
    amount: 150000,
    date: DateTime(2026, 4, 16),
    icon: Icons.medical_services_outlined,
    color: Colors.red,
  ),
  TxModel(
    id: '16',
    title: 'Langganan Netflix',
    category: 'Hiburan',
    type: 'Pengeluaran',
    amount: 54000,
    date: DateTime(2026, 4, 17),
    icon: Icons.tv_outlined,
    color: Colors.deepOrange,
  ),
  // Maret
  TxModel(
    id: '17',
    title: 'Gaji Bulanan',
    category: 'Gaji',
    type: 'Pemasukan',
    amount: 8500000,
    date: DateTime(2026, 3, 1),
    icon: Icons.work_outline,
    color: Colors.green,
  ),
  TxModel(
    id: '18',
    title: 'Belanja Bulanan',
    category: 'Belanja',
    type: 'Pengeluaran',
    amount: 680000,
    date: DateTime(2026, 3, 5),
    icon: Icons.shopping_bag_outlined,
    color: Colors.purple,
  ),
  TxModel(
    id: '19',
    title: 'Tagihan Listrik',
    category: 'Tagihan',
    type: 'Pengeluaran',
    amount: 295000,
    date: DateTime(2026, 3, 8),
    icon: Icons.bolt_outlined,
    color: Colors.amber,
  ),
  TxModel(
    id: '20',
    title: 'Freelance Web',
    category: 'Pendapatan Lain',
    type: 'Pemasukan',
    amount: 2500000,
    date: DateTime(2026, 3, 15),
    icon: Icons.code_outlined,
    color: Colors.blue,
  ),
];


